name: Bandit Scan

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit
      run: bandit -r . --format sarif --output bandit-results.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit-results.sarif
      if: always()
